//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace final_assignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class returnbook
    {
        public int Id { get; set; }
        public int mid { get; set; }
        public string book { get; set; }
        public System.DateTime returndate { get; set; }
        public int elap { get; set; }
        public int fine { get; set; }
    }
}
