//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace final_assignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userrole
    {
        public int Id { get; set; }
        public int userid { get; set; }
        public string role { get; set; }
    
        public virtual master master { get; set; }
        public virtual User User { get; set; }
    }
}
